### ISSUE TITLE
Skill image doesn’t get blurred on card hover

### ISSUE THREAD

**Issue by neamm** [Krumbit/portfolio#12]
Browser: Opera GX
Image:
![image](https://github.com/Krumbit/portfolio/assets/146665856/64319e64-b51e-43d6-bc9e-6999d18fd8d2)

**Comment by Krumbit** [comment]
![image](https://github.com/Krumbit/portfolio/assets/12988040/e8359cc3-a12e-459d-870b-d02702dff9e2)

Can't seem to replicate it

**Comment by neamm** [comment]
### Issue is almost surely on my end. My empty (no extensions etc.) Opera GX profile does not have this issue.
**Marked as resolved by _Neam_.**
